### PR TITLE
Fix diary index generation with custom file extensions

### LINKED ISSUE #302: `:VimwikiDiaryGenerateLinks` does not understand markdown syntax and custom file ext.
```
let g:vimwiki_list = [ {'path': '~/vimwiki', 'syntax': 'markdown', 'ext': '.md.wiki'} ]
```

Create couple of diaries, `:VimwikiDiaryGenerateLinks` - the generated links are using non-markdown syntax and point to wrong directories.

BTW. Vimwiki is awesome.

### PR DESCRIPTION
**Pull request by dpc**
Fix #302

### CODE REVIEW

**Comment by johnmarcampbell** [comment]
I had a look at this...
1) Links now point to the correct files with the correct extensions. Awesome!
2) It looks like links are still created in the non-markdown format. That is, two brackets (`[[link]]`) instead of one (`[link]`). Although I could be missing something, as I don't usually have my vimwiki set up for markdown format.
3) Until we are finished with The Big Refactor, we are merging all changes with the dev branch. Could you change this PR to merge with dev? Or if that's not possible, close this one and open a new one?

Thanks!

**Comment by dpc** [comment]
https://github.com/vimwiki/vimwiki/pull/403

**Comment by dpc** [comment]
I think you're right about the link, but they work and display OK...

**Comment by johnmarcampbell** [comment]
Okay, that sounds good to me. I'll close this PR without merging so that we can focus on the PR for the dev branch.

**Pull request closed without merging**
