### PR TITLE
wiki path processing bug + html export image transclusion bug

### LINKED ISSUE #997: Fundamental link processing bug
Using current master branch, 2020-08-27 (.vimrc below).

There are two fundamental, related bugs:

1. exporting 2 html all does not handle links properly for images down in the hierarchy, and exporting 2 all html does not handle up-links properly.

2. vimwiki highlighting does not handle up-links, and thinks they're broken in highlight, though they work fine to follow. 

This one is obvious, you can see the broken images in export:
image_export_path_broken

The links in red are signaled as broken, but are good links. They work to follow, but NOT in the html export. The other non-highlighted links work in the html export, but not the red ones.
up_back_link_processing_broken

Interestingly, the export works when you export one page at a time, but not when exporting all. Either way, the highlighting is faulty.

This is clearly counter to the wiki spec, and the wiki functionality itself works, but the highlighting does not, and much more critically, the html export does not.

my .vimrc
```
" TODO shift-tab does not work in st but it does in gnome term?
" https://vim.fandom.com/wiki/Make_Shift-Tab_work
"https://www.reddit.com/r/vim/comments/gahih3/suckless_terminal_and_shift_tab/
set t_kB=[Z

set tabstop=4
set expandtab
set shiftwidth=4
set autoindent
set encoding=utf-8
set fileencoding=utf-8
set number
set incsearch
set lbr
set wrap

" powerline options
set laststatus=2
set showtabline=2

"for nerdtree and buffers
let mapleader=","

nmap <leader>nt :NERDTreeFocus<cr>

" For buffer-tab operation
set hidden
nmap <leader>l :bn<cr>
nmap <leader>h :bp<cr>
nmap <leader>b :ls<cr>
nmap <leader>x :bd<cr>

" copy-past to system clipboard
"https://stackoverflow.com/questions/30691466/what-is-difference-between-vims-clipboard-unnamed-and-unnamedplus-settings
"set clipboard=unnamedplus
set clipboard^=unnamed,unnamedplus

" set cursorline
" set spell
" set nospell

" vimwiki says to have these, order matters, here and below
set nocompatible
filetype plugin on
syntax on

" folding for vimwiki
let g:vimwiki_folding = 'expr'

" don't implicitly hijack files everywhere as vimwiki
let g:vimwiki_global_ext = 0

" change dir when navigating to page
" TODO does this really help anything?
let g:vimwiki_auto_chdir = 1

" auto-toc, show broken links
let g:vimwiki_list = [{'path': '~/vimwiki/', 'auto_toc': 1, 'maxhi': 1, 'auto_export': 1}]

" tagbar
nmap <leader>tb :TagbarToggle<cr>

set background=dark
:colorscheme desert
" :colorscheme delek
" :colorscheme slate

" color headers in gradient
highlight VimwikiHeader1 ctermfg=Green
highlight VimwikiHeader2 ctermfg=Green
highlight VimwikiHeader3 ctermfg=Green
highlight VimwikiHeader4 ctermfg=Green
highlight VimwikiHeader5 ctermfg=Green
highlight VimwikiHeader6 ctermfg=Green
let g:vimwiki_hl_headers = 1

" makes diff mode wrap (actually better without it)
"au VimEnter * if &diff | execute 'windo set wrap' | endif

" diff mode colors sucked in general
if &diff
    highlight DiffAdd    ctermbg=237
    highlight DiffDelete ctermbg=237
    " DiffChange should not really be highlighted
    highlight DiffChange ctermbg=233
    highlight DiffText   ctermbg=237
endif
```

### PR DESCRIPTION
**Pull request by BehindTheBrain**
Fixes #997, #354, and #581 (see those for discussion).

### CODE REVIEW

**Comment by tinmarino** [comment]
It breaks VimwikiRenameLink ([test](https://travis-ci.com/github/vimwiki/vimwiki/jobs/385711068)) and is not properly linted ([test](https://travis-ci.com/github/vimwiki/vimwiki/jobs/385711065)).

Also it would be nice to add some non-regression tests, at least as comment.

**Comment by BehindTheBrain** [comment]
Thanks. It didn't break rename for me. Yes, I know "it works on my machine" is not good enough :) Time to learn one more testing framework I guess -- the tests didn't run locally for me upon quick attempt. May take me a couple weeks (or more).

**Comment by tinmarino** [comment]
Only one test is failing (over 400) so I recommend bombarding the github travis in a temporary branch.

**Comment by tinmarino** [comment]
It seems that this PR breaks more tests than issues it revendicates to fix.
Thanks for the contribution but it is not production ready.

**Pull request closed without merging**
