### PR TITLE
Fix sorting order of tags.

### PR DESCRIPTION
**Pull request by t7ko**
Before the fix, tags file sorting was done alphabetically.  That would treat line numbers as strings, and so, for example, if the same tag was placed on the same page on lines, say, 9 and 114, the order you would get, 114 would go first, instead of 9.

Fix adds proper entries comparison to the sort function.

### CODE REVIEW

**Comment by t7ko** [comment]
@EinfachToll could you pls check whether the fix looks good to you?

The scenario I'm fixing is:

* Enable tags.
* Open any page.
* Put a tag `:test:` on any line in range 3-9, but not below the header (so that tag stays on its own).
* Put another instance of the same tag on any line after 10, but again not below the header.
* Save.
* Run `:tag test`.

**Expected:** jumps to the first instance, at the beginning of file.

**Actual:** jumps to the last one.

**Comment by t7ko** [comment]
Note: this is a bugfix to a feature added in #85.

**Comment by EinfachToll** [comment]
Hm, so actually the tags file will be not sorted, although the first line in the tags file says so. I don't know if that always yields the correct result.
An easier and perhaps safer solution would be to just prepend the line number with zeros before sorting:
~~~viml
      call add(tags,
            \   entry.tagname  . "\t"
            \ . pagename . VimwikiGet('ext') . "\t"
            \ . repeat("0", 6 - strlen(entry.lineno)) . entry.lineno
            \ . ';"'
            \ . "\t" . "vimwiki:" . entry_data
            \)
~~~
It's not that elegant, but works.

**Comment by t7ko** [comment]
As far as I understand, sorting is only required for tags; that is later used to do binary search to locate tag information.  Sorting the entire file is not strictly required.

Anyway.

Would you like me to apply your change and merge it into `dev`?

**Comment by EinfachToll** [comment]
No, we can take your solution. I was only a little concerned about performance at first, but in my quick tests I hardly noticed a slowdown even with a thousand tags.

**Comment by t7ko** [comment]
Well, I'll merge it then.

**Pull request merged**
