### PR TITLE
WIP: Clean tasks that are done

### PR DESCRIPTION
**Pull request by Nudin**
Adds functions to clean up you todo-lists by removing all items marked as done.

### CODE REVIEW

**Comment by Nudin** [comment]
At the moment `vimwiki#lst#remove_done` doesn't do anything if start of end is not a line with a todo-item. I copied this behavior from `vimwiki#lst#remove_cb` – but I don't think it's rational. I'd like to change it in both functions, that it cleans all todo-items in the selection.

Example:
```
- [ ] foo1
- [ ] foo2
- [ ] foo3

- [ ] bar
```

- vimwiki#lst#remove_cb(1, 3) removes the checkboxes in line 1 to 3
- vimwiki#lst#remove_cb(1, 5) removes the checkboxes in line 1 to 3 and line 5
- vimwiki#lst#remove_cb(1, 4) doesn't do anything.

**Comment by johnmarcampbell** [comment]
I looked at this a little bit. It looks like `VimwikiRemoveDoneInList` doesn't remove sub-items. For instance
```
 * [ ] Item1
 * [X] Item2
 * [X] Item3
   * [X] Item3a
 * [X] Item4
 * [ ] Item5
```
becomes 
```
 * [ ] Item1
   * [X] Item3a
 * [ ] Item5
```
Would it be easy to modify this to also remove sub-items?

**Comment by hq6** [comment]
I suspect this PR has to be updated. If I merge it into the current `dev` branch and execute `VimwikiRemoveDoneInList`, I get the following errors:

```
Error detected while processing function vimwiki#lst#remove_done_in_list:
line    7:
E117: Unknown function: s:remove_done
E15: Invalid expression: s:remove_done(cur_item)
E117: Unknown function: s:remove_done
E15: Invalid expression: s:remove_done(cur_item)
E117: Unknown function: s:remove_done
E15: Invalid expression: s:remove_done(cur_item)
E117: Unknown function: s:remove_done
E15: Invalid expression: s:remove_done(cur_item)
```

**Comment by Nudin** [comment]
Yes, I havn't deen working on this for too long… I still plan to finish this at some point. By changes in my usage of vimwiki I would need this again more often than in the last year, so mybe soonish I'l takle this again.

**Comment by tinmarino** [comment]
I would love this feature ! Actually without it, I don't use todo list style
I would even backup the deleted lines to keep a trace of work done to know what I did on September 2017 if someone ask. As (bad) example, here is my own backup script (only for my `todo` wiki [and not the `reference` one):

```vim
" Autobackup deleted lines if todo
augroup done_textyankpost
  autocmd!
  autocmd TextYankPost */wiki/todo/*.md  call <SID>textyankpost(v:event)
augroup END


" Callback : autobackup
function! s:textyankpost(dict)
  " Check
  if v:event['operator'] != 'd' | return | endif
  if expand('%:$') =~  '/wiki/todo/done.md' | return | endif

  " Append to done
  let l:new_line = a:dict['regcontents']
  let l:new_line[0] = strftime(">%Y/%M/%d at %X : ") . l:new_line[0]
  call writefile(l:new_line, $done , 'a')
endfunction
```

**Comment by ranebrown** [comment]
Closing this since it isn't being worked and is referenced in an open issue.

**Pull request closed without merging**
