### PR TITLE
Add an option to conceal preformatted text markers

### PR DESCRIPTION
**Pull request by gpanders**
This PR adds a feature allowing users to conceal code fence markers. 

For example, if you have the following in your wiki:

````
Some text

{{{python
def hello_world():
    print("Hello world!")
}}}
````

then setting `g:vimwiki_conceal_code_blocks` would conceal the `{{{python` and `}}}` lines to produce:
````
Some text


def hello_world():
    print("Hello world!")

````

This can make things look a lot nicer and more polished in wikis with many code blocks.

Note that this only applies to blocks that are syntax highlighted. So plain blocks that use just `{{{ }}}` (with no syntax highlighting) will not be concealed.

### CODE REVIEW

**Comment by hq6** [comment]
Please fix the conflicts and force-push.

Also, what is the reasoning for handling syntax highlighted blocks differently than other pre-formatted text?

**Comment by gpanders** [comment]
No particular reason, I can modify it to include all pre-formatted text.

**Comment by gpanders** [comment]
Conflicts have been resolved. This is ready for merge.

**Comment by hq6** [comment]
I have manually merged this in `e56c26c7ba892fc6ee073df0f2457d899d24d433` to have a cleaner history.

**Pull request closed without merging**
