### PR TITLE
Issue 970

### PR DESCRIPTION
**Pull request by jeromg**
Steps for submitting a pull request:

- [X] **ALL** pull requests should be made against the `dev` branch!
- [X] Take a look at [CONTRIBUTING.MD](https://github.com/vimwiki/vimwiki/blob/dev/CONTRIBUTING.md)
- [X] Reference any related issues.
- [X] Provide a description of the proposed changes.
- [ ] PRs must pass Vint tests and add new Vader tests as applicable.
- [ ] Make sure to update the documentation in `doc/vimwiki.txt` if applicable, 
      including the Changelog and Contributors sections.

I think I messed things up on my side while rebasing my PR. I'm submitting a new PR.

After debugging, I made the following change which seems to work fine on my end, but after somehow managing to run the tests on Win10 using WSL2, the tests seem to fail somewhere else (apparently unrelated to this change): `Too many arguments for function: vimwiki#base#apply_template`

I ended up changing the following line:
```
  let l:matching_files =
        \ filter(l:normalised_file_paths, "v:val ==# '" . a:filename . "'" )
```

Sorry as I have never developed a vimscript (even though I'm a long time vim user) and I'm not familiar with the Github's PR process.

### CODE REVIEW

**Comment by tinmarino** [comment]
> Sorry as I have never developed a vimscript (even though I'm a long time vim user)

Well not so bad.

> and I'm not familiar with the Github's PR process.

This is kind of bad :-)because
1. your PR is towards master and should be towards dev.
2. your branch originate form master and add the commit one by one IDK how, you should:

```bash
git checkout dev
git checkout -b work_branch
git cherry_pick ae7b779
git push 
```

Create PR towards dev

**Comment by tinmarino** [comment]
Form my side:

```
git fetch wiki pull/974/head:test_974   # Still your code from PR number
git checkout test_974
git rebase top_tin  # top_tin is my personal work branch
git ck top_tin
git rebase test_974
git push   # By default in my branch
```

And [there](https://github.com/tinmarino/vimwiki/commit/b1de908f0eba603dd4d5b5747990478a50dfbffd) you see your changes in my repo.

Waiting for the tests ....

OK then I push to dev

And your code is integrated [there in dev](https://github.com/vimwiki/vimwiki/commit/b1de908f0eba603dd4d5b5747990478a50dfbffd)

**Comment by tinmarino** [comment]
To resume, fixed by you if it fixes your code.
Anyway you solved a bug for whitespaces for other people too, the commit is very small so good job.

See you in an other PR, Issue. Open source is nice to practice, you can follow with some [good first issue](https://github.com/vimwiki/vimwiki/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22), it would be really apreciated

**Comment by jeromg** [comment]
Thanks a lot @tinmarino I guess I need to pump up my git skills!
I'll have a look at other 'good first issue', that will be my contribution to the community.

**Comment by tinmarino** [comment]
@jeromg , I'm really sorry for not replying <=  I thought I did. Fortunately I came back here to get my git notes.

> I didn't update the changelog in vimwiki.txt

I did it in 5c64ced22dcf5579a5 for your PR #982

**Pull request closed without merging**
