### PR TITLE
Add %wiki_path% template variable.

### PR DESCRIPTION
**Pull request by HugoNikanor**
I needed a %wiki_path% variable for a git integration script I'm writing. I also thought that up-streaming it would be a good idea.

Recreated issue to point at different branch in my fork.

### CODE REVIEW

**Comment by EinfachToll** [comment]
Ok, this may be useful for some users. If you would add a remark about it to the "Placeholders" section of the doc, this would be even greater.

**Comment by HugoNikanor** [comment]
I added a short piece of documentation. See the second commit.

**Comment by HugoNikanor** [comment]
Ping. Will this be merged?

**Comment by hq6** [comment]
@HugoNikanor , I am a new maintainer and I'm interested in getting this merged. 

It seems that all the other placeholder variables start with a `%` but do not end with a `%`. Is there a good reason for `%wiki_path%` to break this convention?

**Comment by HugoNikanor** [comment]
@hq6 As far as I can see the placeholder variables use two `%` characters in the HTML template file (default.tpl), and only a single leading `%` from inside the .wiki files.

**Comment by hq6** [comment]
@HugoNikanor , In that case, should `doc/vimwiki.txt` have only a leading `%`?

This current PR shows `%wiki_path%` in that file.

**Comment by hq6** [comment]
Sorry I think I just realized why I was confused.  If my new understanding is correct, `%wiki_path%` **is only meant to be used in the HTML template** files and never in the `.wiki` files. However, everything else in the Placeholders documentation is referring to directives placed **inside wiki files**.

Please correct me if my new understanding is wrong.

If I have understood this correctly, I think it would be more clear to document this in the description of `vimwiki-option-template_path` instead, as a section of "Additional Template Variables", and leave it out of Placeholders.  I realize that @EinfachToll  asked you to put it in Placeholders, but I hope both of you can understand why this might cause confusion.

@HugoNikanor, what are your thoughts on this?

**Comment by HugoNikanor** [comment]
@hq6. I agree with you on the confusion. I submitted a new commit which moves the documentation.

**Pull request merged**
