### PR TITLE
fix broken diary listing generation, #921

### PR DESCRIPTION
**Pull request by sdondley**
This seems to fix generation of diary index page.

### CODE REVIEW

**Comment by tinmarino** [comment]
Hi again @sdondley. I'm gonna code today. So will integrate (or not) this fast: let's work together!
Can you send me here some info for making a test ? File_pre : command : File_post that used to not work and now are working please: I am gonna do the test if you agree.

**Comment by sdondley** [comment]
Sorry, I have no idea how write tests for vim and I barely know vimscript.

**Comment by tinmarino** [comment]
After tests: if the chnages are only for Diary, do not modify update_buffer because all rely on its behavior: I dont think all are adding a counter bug before calling so the bug must be before in the call stack

**Comment by tinmarino** [comment]
> Sorry, I have no idea how write tests for vim and I barely know vimscript.

That is why I am gonne code its: just past them here. I mean the :VimwikiDiaryGenerateLinks is working well for me so if you can reprodude, can you add some screenshots

**Comment by sdondley** [comment]
diary generation

**Comment by tinmarino** [comment]
@sdondley how do you add the keystrokes in the video ?

**Comment by sdondley** [comment]
Screenflick. 

I did a little write up about looking for a good screen capture program: https://steve.dondley.com/Screen-capture-solutions/

**Comment by tinmarino** [comment]
> Screenflick.

Thanks

You are at the good place in update_in_listing finally but it is a hard-to-read function.
The best would be to comment it a little.

Finally I did a hacky changing fold level at start and at end of this function. The commit reference the issue.

**Comment by sdondley** [comment]
Thanks! It looks like it's working now. My listing no longer disappears when I do `<leader>wi`

**Comment by tinmarino** [comment]
I felt free to close the PR

**Comment by sdondley** [comment]
I am unable to close issue even on my own projects. I think there must be some kind of javascript issue with safari.

**Pull request closed without merging**
