### PR TITLE
Open wiki in a split pane

### PR DESCRIPTION
**Pull request by danetrata**
Opening a wiki in a split pane added to function base#goto_index() through the 'tabedit' argument.
The function can now take the following:
```
vimwiki#base#goto_index(..., [1, 2, 3])
1       tabedit
2       split
3       vsplit
```

The change does not affect any other function calls because all the other function calls assumed '1' to be 'tabedit'.

### CODE REVIEW

**Comment by Nudin** [comment]
@danetrata: Thanks for contributing! And sorry for the long delay.
Can you please add consistent behavior to the diary (`vimwiki#diary#make_note` in diary.vim) – then I will happily merge the patch.

**Comment by danetrata** [comment]
Thanks for looking at the PR! 
I just wanted to leave a note how I use it.

`    nnoremap <Leader>wp :call vimwiki#base#goto_index(v:count, 3)<cr>
`

**Comment by Nudin** [comment]
Merging now. Not sure if/how we could document this…

**Comment by EinfachToll** [comment]
@Nudin we need to introduce new commands similar to VimwikiIndex and VimwikiTabIndex and document these commands.

**Pull request merged**
