### PR TITLE
Fix regex checks

### PR DESCRIPTION
**Pull request by sdondley**
need ampersand to get value of foldmethod

Steps for submitting a pull request:

- [ ] **ALL** pull requests should be made against the `dev` branch!
- [ ] Take a look at [CONTRIBUTING.MD](https://github.com/vimwiki/vimwiki/blob/dev/CONTRIBUTING.md)
- [ ] Reference any related issues.
- [ ] Provide a description of the proposed changes.
- [ ] PRs must pass Vint tests and add new Vader tests as applicable.
- [ ] Make sure to update the documentation in `doc/vimwiki.txt` if applicable,
      including the Changelog and Contributors sections.

### CODE REVIEW

**Comment by tinmarino** [comment]
It is the cutom vimwiki folding method: `:h vimwiki-folding` and `:h g:vimwiki_folding`

**Comment by tinmarino** [comment]
See previous comment. The changes do not seem good.
Also the PR must be made towards the dev branch.
Sorry ...

**Comment by sdondley** [comment]
I have no idea what that comment means but the code is fundamentally broken. It always falls through to `setlocal foldmethod=manual`

**Comment by tinmarino** [comment]
> I have no idea what that comment mean

A pull request is a proposition to merge your personal branch in the common branch. For vimwiki the common branch to use is `dev`. There is a little scrolldown menu creating the PR (Pull Request)

> the code is fundamentally broken.

Do your changes fundamentally repair it ? In which case, it is important to give (at least in the PR) some test or see repo tets so that we don't break it again in the future

> It always falls through to setlocal foldmethod=manual

w should have a look at that.

**Comment by sdondley** [comment]
Sorry, don’t have the spare cycles to do all that. You should have someone look at it, though.

**Pull request closed without merging**
