### PR TITLE
Multiline bullet-lists, HTML comments and TODO

### PR DESCRIPTION
**Pull request by silvioricardoc**
This patch changes a couple of little details. I split it in 3 commits, but maybe I should have split it in 3 patches? Anyway, here they are:

1. Allow HTML-style comment syntax, such as `<!-- my comment -->`, which is officially part of markdown.

2. Treat highlighted bullet-point entries spanning multiple lines as a single entity. This happens when we have a checked [X] item whose text continues on the next line.

3. Avoid matching "TODO" on word boundaries (e.g. does not match "xTODO:"). Also, with this patch, the ":" after TODO is not required (so e.g. "[TODO]" also works).

### CODE REVIEW

**Comment by EinfachToll** [comment]
1. and 3. are fine, but I don't get number 2. Can you post an example when a bullet point is not threated correctly?

**Comment by silvioricardoc** [comment]
```
* [X] This example should be highlighted
      as a single entity, meaning that all of these lines
      should be shown as a Comment when [X] is checked.
* [ ] This line should not be highlighted, OTOH.
```

**Comment by EinfachToll** [comment]
There is already the option `g:vimwiki_hl_cb_checked`. Setting this to 2 should do what you want. Or is there still a difference?

**Comment by silvioricardoc** [comment]
Oh wow, I completely missed that. It works great when I set it to 2, so I agree we can skip number (2) above.

Would you still accept (1) and (3)? Should I create another pull request with only these?

**Comment by EinfachToll** [comment]
Yes, (1) and (3) are ok. You probably don't need to open a new PR, but you can perhaps add a new commit to your `multiline-and-comments` branch where you revert (2) or something like that. Github became a bit complicated over the last years 😮

**Comment by EinfachToll** [comment]
👍

**Pull request merged**
