### PR TITLE
Functions to remove all todo items that are done

### LINKED ISSUE #823: Archive todo lists
Would be nice to have for Vimwiki, was using it back when i was on Sublime text with [PlainTask](https://packagecontrol.io/packages/PlainTasks) they had it so you could put the archive under the list or in a separate file, really great way to keep track on what has been done and to keep your current list from getting to big with things you already completed.

up

Maybe i should get another plugin for task management but i thought it would be a good ide for Vimwiki

### PR DESCRIPTION
**Pull request by Nudin**
This adds functions that remove todo items that are marked as done.

* `VimwikiRemoveDone`/`vimwiki#lst#remove_done` removes them within the selected area.
* `VimwikiRemoveDoneInList`/`vimwiki#lst#remove_done_in_list` removes them in the list the cursor is in.
  * `vimwiki#lst#remove_done_in_list` has a parameter to define if it should work recursively. Default is not recursive.

Superseeding #391
Fixes #823 and others.

### CODE REVIEW

**Comment by Nudin** [comment]
The documentation still has to be improved. I wasn't sure if we should define both commands and whether default should be recursive or not. Recursive has the somewhat surprising but correct side effect that the status of items can decrease. See the test for example.

@tinmarino @rane-brown any thoughts?

**Comment by tinmarino** [comment]
I would put recursive as default: to get most work done which is harder to do by hand.

Very readble tests, really awesome.
Reading the last one, with spaces suprised me it was considered as a single list but better. Can you add tests for the behavior of 2 lists with content in between ?

```
* [X] Done 1
* [ ] Todo 1

This should break the list

* [ ] Todo Post space
* [X] Done Post space
```

**Comment by ubitux** [comment]
It probably doesn't belong in this PR, but what about multi-line TODO entries? I often use `gq` and ends up with multi-line entries, and I know they're not well supported in vimwiki (at least in markdown `let g:vimwiki_hl_cb_checked = 1` will only gray-out the first line). So I'm curious how the removal of this PR behaves here in that situation.

**Comment by Nudin** [comment]
> I would put recursive as default: to get most work done which is harder to do by hand.

Good argument, I changed it to recursive and updated the tests accordingly.

> Reading the last one, with spaces suprised me it was considered as a single list but better. Can you add tests for the behavior of 2 lists with content in between ?

I actually found out about this behavior by your `list_update.vader` tests. ;) This PR doesn't change anything on the general behavior of list but reuses existing functions.

> It probably doesn't belong in this PR, but what about multi-line TODO entries? I often use `gq` and ends up with multi-line entries, and I know they're not well supported in vimwiki (at least in markdown `let g:vimwiki_hl_cb_checked = 1` will only gray-out the first line). So I'm curious how the removal of this PR behaves here in that situation.

Yes, better create a ticket for that (if it doesn't exist yet).

**Pull request merged**
