### PR TITLE
Generate RSS feed for diary

### PR DESCRIPTION
**Pull request by reinerh**
This change allows one to generate an RSS feed for the exported VimWiki (#172).
It introduces the command `:VimwikiRss` which generates a rss.xml file (filename can be changed via `rss_name` setting)
that contains the latest diary entries (by default 10; configurable via `rss_max_items`).

- [x] **ALL** pull requests should be made against the `dev` branch!
- [x] Take a look at [CONTRIBUTING.MD](https://github.com/vimwiki/vimwiki/blob/dev/CONTRIBUTING.md)
- [x] Reference any related issues.
- [x] Provide a description of the proposed changes.
- [x] PRs must pass Vint tests and add new Vader tests as applicable.
- [x] Make sure to update the documentation in `doc/vimwiki.txt` if applicable,
      including the Changelog and Contributors sections.

### CODE REVIEW

**Comment by tinmarino** [comment]
Hi Reinerh,

Thank for the contribution.
This seems to be a very good job but I can't review easily. I think the integration would help some people. For example you on another machine.
Seeing all the effort you made I would ask you to add some conversion non regression tests: with the vader framework or copy pasted here and I manage the Vader format. You must explicit In and Out and user interaction, conf.
Also this is not Vint compliant (that is why it breaks the tests):

```
Starting Docker container and running Vint.
autoload/vimwiki/html.vim:1499:1: Use the abort attribute for functions in autoload (see Google VimScript Style Guide (Functions))
autoload/vimwiki/html.vim:1602:1: Use the abort attribute for functions in autoload (see Google VimScript Style Guide (Functions))
autoload/vimwiki/html.vim:1836:14: Use robust operators `==#` or `==?` instead of `==` (see Google VimScript Style Guide (Matching))
```

So to resume:
1. Add some non regression test (or instructions on how to do some of them, working on your machine)
2. Lint your code o be Vint compliant

Thank for your comprehension,

**Comment by reinerh** [comment]
Thanks @tinmarino for having a look.
I just added Vader tests and fixed the linter warnings.

I think it's easier to review the commits individually, as the first commit was just doing some refactoring (moving around some code with different indentation, which blows up the diff).

**Comment by tinmarino** [comment]
> Thanks @tinmarino for having a look.
> I just added Vader tests and fixed the linter warnings.
> 
> I think it's easier to review the commits individually, as the first commit was just doing some refactoring (moving around some code with different indentation, which blows up the diff).

Awesome ! 1/ Nice tests, 2/ pretty commit factoring, 3/ Really fast reacting.

I rebase all 3 to dev (without squashing).

**Comment by tinmarino** [comment]
Lol, this feature only costed me once click :-)
Thanks @reinerh

**Pull request merged**
