### PR TITLE
fixed #272

### LINKED ISSUE #272: Not support markdown header syntax by symbol "-" and "=" underline
markdown HEADER1 and HEADER2 has another format
eg:

This is Header1
========

This is Header2
--------

### PR DESCRIPTION
**Pull request by icersong**
fixed #272

### CODE REVIEW

**Comment by icersong** [comment]
Markdown syntax hilight for header with ---- and ====

**Comment by EinfachToll** [comment]
Uh, what happend to this PR? Why does it contain so much stuff which is already in the code? Any chance to rebuild the PR?

**Comment by hq6** [comment]
There have been no updates since EinfachToll's last comment, so I am closing this PR due to staleness.

**Comment by Nudin** [comment]
Since the "real content" of this PR is just two lines and it would apparently fix an often asked issue it might be worth trying out if that works and has no negative side-effects and if so make a new PR.

**Pull request closed without merging**
