### PR TITLE
Fix Renaming and HTML Exporting Issue

### PR DESCRIPTION
**Pull request by levirs565**
Steps for submitting a pull request:

- [x] **ALL** pull requests should be made against the `dev` branch!
- [x] Take a look at [CONTRIBUTING.MD](https://github.com/vimwiki/vimwiki/blob/dev/CONTRIBUTING.md)
- [x] Reference any related issues.
- [x] Provide a description of the proposed changes.
- [x] PRs must pass Vint tests and add new Vader tests as applicable.
- [x] Make sure to update the documentation in `doc/vimwiki.txt` if applicable,
      including the Changelog and Contributors sections.

This pull request fix these bugs:
- Renaming, Updating Link, and HTML Export in Windows. This fixed by using nicer way to getting sudbir.
- Custom HTML Shell execution escaping failed in Windows when in root dir.
- Custom HTML CSS path is wrong.

### CODE REVIEW

**Comment by levirs565** [comment]
**Before this Pull Request merged we must confirm that referenced Issue is fixed or not**

**Comment by tinmarino** [comment]
Please ping me when ready.

**Comment by levirs565** [comment]
You can merge this PR

**Comment by levirs565** [comment]
This Pull Request is Ready for Merging

**Comment by tinmarino** [comment]
Merging: I do not have time to test it on Windows but it does not break the currents test battery.
Marked the related issues to be closed before v2.6.

@levirs565 you may send some examples of situations where there were bugs formerly so that we can add some non-regression tests. One day Windows platform may be included in those tests (it is supported by Travis)

**Pull request merged**
