### PR TITLE
#940: Render header inside thead element if table has header

### PR DESCRIPTION
**Pull request by gaurangkher**
Ref:https://github.com/vimwiki/vimwiki/issues/940

Added functionality for table html conversion:
If table header has been specified in vimwiki, headers will go under thead element and rest will go under tbody element

### CODE REVIEW

**Comment by tinmarino** [comment]
Nice job.
Would you mind adding some non regression tests ?
with head, without head, with more than one line in the body

**Comment by gaurangkher** [comment]
@tinmarino glad you like the change. To be honest though I am not well versed with vimscript or vader. 
Some pointers on a similar test or where to start will be really helpful. Thanks!

**Comment by tinmarino** [comment]
[Readme](https://github.com/vimwiki/vimwiki/blob/dev/test/README.md) for vimwiki tests
[html conversion tests](https://github.com/vimwiki/vimwiki/blob/dev/test/convert_default_html.vader) vimwiki
[Vader](https://github.com/junegunn/vader.vim) repo

Install and run Vader on some existing tests. Run vim -u test/vimrc to be independant from your personal configuration.

**Comment by tinmarino** [comment]
I refactored the tests because it was very hacky, an example of converion can be found [here in dev](https://github.com/vimwiki/vimwiki/blob/2332dc15149e52d80e89663471eeb29e575ceb32/test/convert_default_html.vader#L9-L60) were I introduced the `ConvertWiki2Html()` function in the [test/vimrc](https://github.com/vimwiki/vimwiki/blob/2332dc15149e52d80e89663471eeb29e575ceb32/test/vimrc#L196-L232).

Also if you load vader `packadd vader` the syntax highlighting is much better (screenshot with [gruvbox colorscheme](https://github.com/morhetz/gruvbox))

Screenshot from 2020-07-29 23-39-20

**Comment by gaurangkher** [comment]
Thanks for the unit tests! I think I got a hang of it from your unit test. Next time I should be equipped!

**Pull request merged**
