### PR TITLE
Logo Proposal, Screenshots & CSS Styles

### PR DESCRIPTION
**Pull request by monkinco**
Everything in ```doc``` folder, with updated README to host all images.

### CODE REVIEW

**Comment by monkinco** [comment]
I have also added new CSS styles for generated documents, they look like this: https://imgur.com/a/myaYp02

**Comment by ranebrown** [comment]
@monkinco Is there any chance the changes to the default css will cause errors on different machines i.e. missing fonts etc.?

I think it would look better to move the logo to the very top of the readme and just replace the "VimWiki" in the header with the logo instead of having it in the intro. What do you think?

**Comment by monkinco** [comment]
> @monkinco Is there any chance the changes to the default css will cause errors on different machines i.e. missing fonts etc.?

I only changed colors, paddings and margins, fonts are system default also. So nothing could be broken.

> I think it would look better to move the logo to the very top of the readme and just replace the "VimWiki" in the header with the logo instead of having it in the intro. What do you think?

Will move it but I don't want to replace VimWiki text, as not everyone will see the logo. It is worth leaving it there. :)

**Comment by monkinco** [comment]
I left the SVG logo in the doc folder, and change it to small splash image in README.

**Comment by monkinco** [comment]
Ok, I removed header and it looks better. 👍

**Comment by ranebrown** [comment]
@monkinco still working on this or is it ready to merge?

**Comment by ranebrown** [comment]
Just noticed it might be a good idea to leave the original screenshots for the Chinese translation since that page hasn't been updated (`README-cn.md`).

**Comment by monkinco** [comment]
> Just noticed it might be a good idea to leave the original screenshots for the Chinese translation since that page hasn't been updated (`README-cn.md`).

I'll add them back with few CSS changes. After that it will be ready to merge.

**Comment by monkinco** [comment]
Screens are back, and it's ready to be merged.

**Comment by ranebrown** [comment]
@monkinco Can you clean up the commit history before I merge this? A good resource is located [here](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history) or you can do `git reset --soft HEAD~9` and then commit all the changes as a single commit. Thanks!

**Comment by monkinco** [comment]
> @monkinco Can you clean up the commit history before I merge this? A good resource is located [here](https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history) or you can do `git reset --soft HEAD~9` and then commit all the changes as a single commit. Thanks!

Done.

**Pull request merged**
