### PR TITLE
fix list folding bug #680

### PR DESCRIPTION
**Pull request by sdondley**
For #680 

I think this should fix it. Seemed to work in my limited manual testing.

### CODE REVIEW

**Comment by ranebrown** [comment]
Your change doesn't seem to work correctly. The example from the linked issue doesn't fold at all for me. I think this needs some more thorough testing.

**Comment by sdondley** [comment]
Can you confirm you have `g:vimwiki_folding` set to "list"?

**Comment by sdondley** [comment]
Here's a gif movie of it working for me.

fold_recording

**Comment by ranebrown** [comment]
Seem to be related to having multiple lists or maybe mixed checkboxes. I didn't really dig into it much. With the below two lists nothing in the second one is folded.
```
- [ ] list 
    - [ ] blah
    - [ ] another item
        - info
        - more stuff
        - link

* [ ] Do stuff 1
    * [ ] Do substuff 1.1
    * [ ] Do substuff 1.2
        * [ ] Do substuff 1.2.1
        * [ ] Do substuff 1.2.2
* [ ] Do stuff 2
* [ ] Do stuff 3
```

**Comment by sdondley** [comment]
Ok, see last patch. I tried to avoid using differences in indentation because, according to line 485 of the "lst.vim" file: "child items do not necessarily have the same indent, i.e. level".  But I don't see an obvious way to avoid using the indent level. It's the only way to determine how many fold levels less the current line is from the previous line. I discovered It's impossible to get the parent level for an item with `foldlevel(parent.lnum)` because, according to the documentation, vim returns -1 until all the fold levels have been determined.

Also, I should note, the vim docs recommend against using 's1', 'a1', 's2' to add and subtract fold levels as it's slow.

But this is at least an improvement and it's a lot better than ripping the guts out of how folds are calculated.

**Comment by ranebrown** [comment]
Thanks for the quick turnaround on this! It does seem to be working better now. I noticed that the two lists get folded together even if there is text in between them. That seems to be the same behavior prior to your change but I don't know that it makes sense. I would think separate lists should be separate folds. What do you think?

**Comment by sdondley** [comment]
I'm seeing two different lists fold. See gif.

**Comment by ranebrown** [comment]
Using this text and closing the fold on 'bar' folds everything below that:
```
= Page =

- bar
   - bar 1
   - bar 2
      * baz

== section ==

- [ ] Do stuff 1
    - [ ] Do substuff 1.1
    - [ ] Do substuff 1.2
        - [ ] Do substuff 1.2.1
        - [ ] Do substuff 1.2.2
- [ ] Do stuff 2
- [ ] Do stuff 3
```

It does work correctly in certain situations but I'm not sure why.

**Comment by sdondley** [comment]
You have to be sure your tabstop and and shiftwidth are the same and that each line is indented by that amount. If they are, it works:

**Comment by sdondley** [comment]
In you sample, the sub-bullets in the first list are only indented by 3. It's probably possible to tweak the indentation calculation to try to "round" which tab stop the line is at. But 90% of people are just going to use regular tab stops. If they don't, they can write their own folding function.

**Comment by ranebrown** [comment]
Ah, makes sense. I just had some random stuff pasted in the file and didn't notice the different indentation.

**Pull request merged**
