### PR TITLE
README.md: point to libera.chat channel (#1167)

### PR DESCRIPTION
**Pull request by brennen**
README.md: point to libera.chat channel

Per discussion in #1131 and libera.chat `#vimwiki`.

Co-authored-by: KaiserBarbarossa <kaiser.barbarossa@yandex.com>
Co-authored-by: Brennen Bearnes <code@p1k3.com>

### CODE REVIEW

**Comment by tinmarino** [comment]
@brennen  you created the PR towards master. Which is fine in the case but please also update the dev branch

**Comment by brennen** [comment]
> @brennen you created the PR towards master. Which is fine in the case but please also update the dev branch

dev was updated a while ago.

**Comment by brennen** [comment]
I'm not authorized to merge to master, evidently. If someone else could click the button, that'd be cool.

**Comment by tinmarino** [comment]
Hi @brennen, I cannot either.
@Nudin could you merge please ?

**Comment by Nudin** [comment]
Sorry for long delay. I added Tinmarino to maintainers, you should now also be able to merge such PR!

**Pull request merged**
