### PR TITLE
Issue 970

### PR DESCRIPTION
**Pull request by jeromg**
Steps for submitting a pull request:

- [x] **ALL** pull requests should be made against the `dev` branch!
- [x] Take a look at [CONTRIBUTING.MD](https://github.com/vimwiki/vimwiki/blob/dev/CONTRIBUTING.md)
- [x] Reference any related issues : Issue #970 
- [x] Provide a description of the proposed changes.
- [x] PRs must pass Vint tests and add new Vader tests as applicable : **NOT REQUIRED**
- [X] Make sure to update the documentation in `doc/vimwiki.txt` if applicable : **NOT APPLICABLE**

### CODE REVIEW

**Comment by tinmarino** [comment]
Hello !

Good first PR, Here is my review:

1. Rebase your branch on dev: it is on master and intengrate the bump version ...
2. Make all tests pass: Some tests are not passing because nothing is considered as a diary now.
  - My advice was a first try but apparently bad.
  - debug `vimwiki#base#is_diary_file` with `:debug func vimwiki#base#is_diary_file` then enter in a file (trigger your bug) and VimwikiGenerateLinks : See what is a diary, what is not => I admit  `map is hard to debug.
3. Squash your commits to have only one with a title like `Fix: is_diary_file to support whitespaces (Issue #970)` (I can squash them with github API but you should not trust the reviewer).
4. Add yourself in the contributor list in `doc`

That said, welcome to vimwiki's team!

**Comment by jeromg** [comment]
Hi there,

Sorry if this is a basic problem but I'm struggling running the tests in docker on **Win10**, when I start the `docker run` command to run the tests, I get:

```
Error detected while processing /testplugin/plugin/vimwiki.vim:
line    8:
E15: Invalid expression: exists('g:loaded_vimwiki') || &compatible^M
line  482:
E171: Missing :endif
```

I know it's an issue with the dos vs unix fileformats in vim, however, even when I force `set ff=dos` I still get this error.

After this, I can still run `Vader test/*` but I then get a similar error due to unexpected eol `^M`:
```
Error detected while processing function <SNR>21_vader[5]..vader#run:
line 116:
Vader error: Vim:E492: Not an editor command: ^M (in /testplugin/ftplugin/vimwiki.vim, line 4)
```
Before I tear my (short) hair, is the test suite supposed to be run from Win10 or shall I just forget it?

Thanks !

**Comment by jeromg** [comment]
I guess I messed things up while rebasing to dev.
I'll fix that on my end and submit a new PR when I'm ready

**Comment by tinmarino** [comment]
> Before I tear my (short) hair, is the test suite supposed to be run from Win10 or shall I just forget it?

The tests do not run very well on Windows, sorry

**Comment by tinmarino** [comment]
But if you manage to make some advances, report them in your PR or as comments in the code.
I worked a little bit on it but, it was far from  perfect when I got tired.

**Pull request closed without merging**
