### PR TITLE
Fixed a syntax highlighting issue of markdown

### PR DESCRIPTION
**Pull request by yuex**
Fixed a markdown syntax highlighting issue. Now, `**strong**` and `__strong__` show bold and `*em*` and `_em_` show italic correctly.

Text objects `ah` and `ih` now support markdown header starting with `#`. And `vih` now selects only contents, leaving the header and blank lines unselected

Added some header motion. Note: Only atx style header of markdown starting with `#` and header of default syntax starting with `=` are supported
`]u` and `[u` - go to upper level header
`]c` and `[c` - go to current header
`]]` - go to next header
`[[` - go to previous header
`]=` - go to next sibling header
`[=` - go to previous sibling header

### CODE REVIEW

**Comment by danielb2** [comment]
How does one enable markdown syntax, and why isn't this getting merged?

**Comment by EinfachToll** [comment]
> How does one enable markdown syntax

By reading the doc ;)  See `:h vimwiki-option-syntax`

> and why isn't this getting merged?

Well, yuex has the rights to push his changes to this repo. But since he didn't, I will try to merge it.

**Comment by danielb2** [comment]
but this is a PR so seems it shuold be merged. Alright, I'll check out the option syntax thing. thanks  man

**Comment by KTSCode** [comment]
so is this going to ever get merged?

**Comment by cjtapper** [comment]
Are there any plans to merge the markdown syntax changes any time soon? I'm finding it frustrating that `vimwiki` doesn't comply with most markdown specs.

**Comment by edubxb** [comment]
Another :cry: user here, hope this PR be finally merged!

**Comment by hq6** [comment]
As a new maintainer, I will take a look at this ancient PR and see if it can be merged.

As I do that, I'd like to solicit comments from the community on whether anything has changed in the last few years that would cause it to no longer make sense to merge this PR.

**Comment by danielb2** [comment]
> As I do that, I'd like to solicit comments from the community on whether anything has changed in the last few years that would cause it to no longer make sense to merge this PR.

I'd say with markdown's popularity growth, quite the opposite. Makes more sense than ever

**Comment by hq6** [comment]
It looks like the conflicts between the current state of `dev` and this PR are semantic rather than syntactic; function signatures have changed.

I do not yet feel comfortable enough with the code base to do this merge safely, so I will defer it until I become more familiar with the code base.

@yuex, if you feel comfortable with resolving the conflicts, I can test and merge sooner.

**Comment by ranebrown** [comment]
See #318

**Pull request closed without merging**
