### PR TITLE
Fix Renaming issue in Windows and ext with two dot

### PR DESCRIPTION
**Pull request by levirs565**
Steps for submitting a pull request:

- [x] **ALL** pull requests should be made against the `dev` branch!
- [ ] Take a look at [CONTRIBUTING.MD](https://github.com/vimwiki/vimwiki/blob/dev/CONTRIBUTING.md)
- [ ] Reference any related issues.
- [x] Provide a description of the proposed changes.
- [ ] PRs must pass Vint tests and add new Vader tests as applicable.
- [x] Make sure to update the documentation in `doc/vimwiki.txt` if applicable,
      including the Changelog and Contributors sections.

In this Pull Request i fix two bugs:
- Rename not work in Windows. Fixed with replace `\` in path with `/`
- Updating link not work when wiki extension contain two dot (eg. `.wiki.md`). Fixed with using regex rather than using `fnamemodify`/`expand`.

I also refractor `vimwiki#base#rename_link` in order to simply the code and make it less bugs.

### CODE REVIEW

**Comment by tinmarino** [comment]
@levirs565 
Thanks for the PR, it seems nice.
May you comment, give a non-regression test?

This forces the '/' delimiter even on Windows. I am in favor of it anyway: it is more transportable

**Comment by levirs565** [comment]
What do you mean?. I am have bad english grammar.

**Comment by levirs565** [comment]
How do i run test?

**Comment by tinmarino** [comment]
You write here an example of a problem you solve.
For example with this file (copy rhe file) I press enter and It does not go to the good file but Vim gives the error (copy the error)

**Comment by levirs565** [comment]
Problem that fixed with this pull request:
1. Renaming page failed in Windows
2. Updating link (after renaming page) failed when wiki extension contain two dot (eg `.wiki.md`)

**Comment by tinmarino** [comment]
Thank you

**Comment by levirs565** [comment]
This pull request now only fix bug renaming in Windows. I have delete the commit that fix bug updating link in two dot ext. I also delete commit that update `doc/vimwiki.txt`. **This pull request is not finished**

**Pull request merged**
