### PR TITLE
VimwikiGoto completion works with part of filename and in nested directories

### PR DESCRIPTION
**Pull request by tinmarino**
Feature: To enable VimwikiGoto command completion to work also:

1. With part of the filename
2. For files in directories

Note: This PR is above PR  #767 -> because I need the vader test framework

### CODE REVIEW

**Comment by ranebrown** [comment]
@tinmarino rebase and I'll try to get this one merged too.

**Comment by tinmarino** [comment]
10 minutes. I'll tell you  I made bad rebase onto ...

**Comment by tinmarino** [comment]
Here we go

**Comment by tinmarino** [comment]
@ranebrown as you seems on a rebase spree. I''ve just made my little last PR request spetll.
But this VimwikiGoto anydir is my favorite feature.
For me, I would even do it fuzzy (you know like ctrlp. I may do it one day.

**Comment by ranebrown** [comment]
It looks like the `VimwikiGoto` command doesn't store the link to the previous page so `<BS>` or `VimwikiGoBackLink` don't work. Do you want to try and add that to this PR (if not I can create a new issue)?

**Comment by tinmarino** [comment]
OK I go for it

**Comment by tinmarino** [comment]
Done adding 1. current file pos and 2. a boolean to `vimwiki#base#edit_file` to trigger this stuff:
https://github.com/vimwiki/vimwiki/blob/2a51d833972e7b36523040b5d512253db0730072/autoload/vimwiki/base.vim#L856-L864)

**Comment by tinmarino** [comment]
I just tried the fuzzy stuff and it is annoying. I don't like. Ctrlp is nice because of the visual of the matched files while typing. And this is some work.

In case someone wants to see it,  or for my own memory;  here is the patch (just add `.\{-}` after each char):
```diff
diff --git a/autoload/vimwiki/base.vim b/autoload/vimwiki/base.vim
index a29783e..1c3d00d 100644
--- a/autoload/vimwiki/base.vim
+++ b/autoload/vimwiki/base.vim
@@ -371,8 +371,11 @@ function! vimwiki#base#get_globlinks_escaped(...) abort
   " convert to a List
   let lst = split(globlinks, '\n')
   " Filter files whose path matches the  user's argument leader
+  let r_arg = s_arg_lead
+  " " use fuzzy matching
+  let r_arg = substitute(r_arg, '.', '\0.\\{-}', 'g')
   " " use smart case matching
-  let r_arg = substitute(s_arg_lead, '\u', '[\0\l\0]', 'g')
+  let r_arg = substitute(r_arg, '\u', '[\0\l\0]', 'g')
   call filter(lst, '-1 != match(v:val, r_arg)')
   " Apply fnameescape() to each item
   call map(lst, 'fnameescape(v:val)')
```

**Pull request merged**
